---

# General configurations
num_rounds: 3
num_clients: 3
batch_size: 16
input_channels: 1
num_classes: 1
num_clients_per_round_fit: 1
num_clients_per_round_eval: 1
image_size: 128
random_seed: 42

# Dataset configurations
train_ratio: 0.9
val_ratio: 0.1
output_dir: "outputs_without_FL/"
dataset_dirs: 
  colon: "/content/drive/MyDrive/UFF/CVC-ColonDB"
  colon1: "/content/drive/MyDrive/UFF/CVC-ColonDB"
  colon2: "/content/drive/MyDrive/UFF/CVC-ColonDB"

# Client training configurations
config_fit:
  lr: 0.001
  min_lr: 0.00001
  weight_decay: 1e-4
  local_epochs: 1